---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: synator
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: synator
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["*"]
  - apiGroups: [events.k8s.io]
    resources: [events]
    verbs: [create]
  - apiGroups: [""]
    resources: [events]
    verbs: [create]
  - apiGroups: [""]
    resources: ["namespaces", "namespaces/status"]
    verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: synator
subjects:
  - kind: ServiceAccount
    name: synator
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: synator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: synator
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: synator
  template:
    metadata:
      labels:
        name: synator
    spec:
      serviceAccountName: synator
      containers:
        - name: synator
          image: josuealcalde/synator:v2.1.0
